//! Diesel table definitions for views.
//!
//! This follows the same general format as the autogenerated `schema` module.
//! Diesel doesn't currently support including views in the generated schema,
//! so these have to live in a separate module so as not to get overwritten
//! every time the main schema changes.

use super::schema::{directories, post_images, posts};

diesel::table! {
    directory_paths (directory_id) {
        directory_id -> Int4,
        path -> Text,
    }
}

diesel::table! {
    post_paths (post_id) {
        post_id -> Int4,
        path -> Text,
    }
}

diesel::joinable!(directory_paths -> directories (directory_id));
diesel::joinable!(post_paths -> posts (post_id));

// Unfortunately we have to do this for each table individually; if we try to
// associate two tables that have already been associated in schema.rs, it will
// complain
diesel::allow_tables_to_appear_in_same_query!(directory_paths, post_paths);

diesel::allow_tables_to_appear_in_same_query!(directory_paths, directories);
diesel::allow_tables_to_appear_in_same_query!(directory_paths, posts);
diesel::allow_tables_to_appear_in_same_query!(directory_paths, post_images);

diesel::allow_tables_to_appear_in_same_query!(post_paths, directories);
diesel::allow_tables_to_appear_in_same_query!(post_paths, posts);
diesel::allow_tables_to_appear_in_same_query!(post_paths, post_images);
